### ISSUE TITLE
Issue with tree ring width

### ISSUE THREAD

**Issue by trotsiuk** [remoteforests/remoteforests_db#1]
Hi @ondrej-vostarek those two trees look suspicious in the end. Please have a look shall you have time

![invalid trw](https://user-images.githubusercontent.com/15097779/44231448-800c6200-a19e-11e8-9769-d998f3570b4a.png)

**Comment by ondrej-vostarek** [comment]
Hi @trotsiuk , concerning the 16305, it is a tree from 2014 SLO  SRA for which I have just recieved corrected data from the lab and I plan to upload the corrected version of chronologies from this stand during tomorrow.

The other tree is from 2015 ROM PAU, it has treetype G but the last increment is realy strange, unfortunately it is the value I have recieved from the lab...

Ondra

**Comment by trotsiuk** [comment]
Thank you much @ondrej-vostarek 
Maybe you can cross-check with Kristina those issues

**Comment by ondrej-vostarek** [comment]
Hi @trotsiuk , I asked Kristyna about the core from PAU and it is probably a knot or bad measurement, however this locality won't be remeasured so I think no one will correct this core, what do you suggest to do with it?

**Comment by trotsiuk** [comment]
Thank you @ondrej-vostarek we need to correct the tree or remove the last ring. IT is obviously not correct, and we don't want to have it in data-base

**Comment by ondrej-vostarek** [comment]
I am for the removal of the last ring, in the case of the other tree which is now correct all the rings were the same except the last one

**Comment by trotsiuk** [comment]
ok, please do it and close the issue

**Comment by ondrej-vostarek** [comment]
the ring is deleted, but I can't closte the issue because I am not assigned to it
