### ISSUE TITLE
Ukraine beech data

### ISSUE THREAD

**Issue by trotsiuk** [remoteforests/remoteforests_db#2]
Ahoj @ondrej-vostarek  I received some more data from the natural beech forest in Ukraine. They are partly structured in the way we keep the database, however additional work is required.

This is not the priority, however if you will find time for it, would be nice to add it to the main database.

The owner is Natalia Rehush

Thank you 

[dendro_ua_rehush.zip](https://github.com/remoteforests/remoteforests_db/files/2571085/dendro_ua_rehush.zip)

**Comment by ondrej-vostarek** [comment]
Ahoj @trotsiuk , 

I am putting this to my to do list :)

Have a nice day,
Ondra.

**Comment by ondrej-vostarek** [comment]
Hi @trotsiuk ,

I finally get to those data and I would like to be sure that: 

1) these are just plot, tree, core and ring data
2) the plot and tree are stored in the 'kel_database_rehush.xlsx' in the same format as we have
3) the core data are stored in the 'kel_database_rehush.xlsx' in a different format
4) the ring data are stored in 'UA_2013_beech.csv'

am I right?

Thanks and have a nice day. 
Ondra

**Comment by trotsiuk** [comment]
Hi Ondra,

yes, sounds correct to me. There might be still small differences in data for plot and tree, as we did certain adjustment. 

The ring data are just exported from the fh file, so basically you need to rearrange them into long format and remove 0's before the chronology starts

Vova

**Comment by ondrej-vostarek** [comment]
Hi @trotsiuk ,

thank you! 

The data are almost prepared for uploading into our database, I just need a few more information:

1) owner's affiliation and email contact
2) the stand names for Bychkiv and Borgawa 
3) should I convert the tree status '1 - alive' into our '1 - alive full' and '2 - dead' into '11 - dead full'
4) concerning the core information 
    a) does some of the columns contain information about missing_mm?
    b) how is the missing_year calculated? I know we use the missing_mm / mean of the first 5 incr,
        however the values in N_in_5 colums does not correspond with the sum of these increments
        calculated from the chronologies
    c) does the blue and read coloring of some of the data have any meaning
    d) why have some of the cores additional treeid in brackets

Thank you in advance for your help. 

Have a nice day!
Ondra

**Comment by trotsiuk** [comment]
Hi @ondrej-vostarek, thanks for a great work

1. Natalia Rhush, Swiss Federal Institute for Forest, Snow and Landscape Research WSL, nataliia.rehush@wsl.ch
2. e.g. BYC and BOR
3. Yes
4. The missing number of rings and distance were calculated using the concentric circles. 
a) I think it is N_missing_circles - I would assume this is a distance to the pith
b) Using concentric circles, similarly as done in the lab. ( I believe).
c) I think read is 'unclear'
d) maybe there are two cores. 

Vova

**Comment by ondrej-vostarek** [comment]
Hi @trotsiuk ,

I have solved most of the things, however, still something remains: 

1) Concerning the missing_years, in the .xlsx they are calculated as N_missing_circles * mean 5 year incr.
    We are using formula missing_mm / mean 5 year incr, therefore I am not sure if the N_missing_circles
    is the distance to the pith in mm.

2) There are 9 cores which are not present in the tree table (one of them has treeid 'NA'), should I create
    and additional "blank" record for them in the tree table? And what about the NA tree?

Thanks for your help! 
Ondra

**Comment by trotsiuk** [comment]
Hi @ondrej-vostarek 

1. Shall we then use the last 5 years mean and multiply by number of years missing, to get distance to the pith?

2. One option would be also to cross-check which trees don't have a core, and if some of them can correspond? Otherwise I would create a black record and remove the NA tree

Vova

**Comment by ondrej-vostarek** [comment]
Hi @trotsiuk ,

1. This can be an option, however, their mean 5 year incr is not corresponding with the one you obtain from the corresponding chronologies, therefore I am not sure which one to use. Also we have the missing_years in the data calculated as the mean 5 incr * N_missing_circles, so the missing_mm would be (mean 5 incr)^2 * N_missing_circles? Another option would be to obtain a table with the number of circles and corresponding distances, similar to the one we are using in our lab - if the methodology is the same, I can ask someone from our lab to provide me with this data. 

2. I have cross-checked the trees, howevere there are more of them from each plot that do not have cores, therefore it is not possible to match them if their id is different. I will folllow your suggestion - create balnk trees and remove the NA one.

Ondra

**Comment by ondrej-vostarek** [comment]
Done.
